#!/usr/bin/perl

# filefuzz flips a certain number of randomly chosen bits in a file, 
# simulating the impact of random small-scale data degradation from eg
# cosmic rays, cable or controller imperfections, etc.
#
# USAGE: filefuzz -i inputfile -b bits -o outputfile [-r]
#
# If bits is greater than or equal to 1, it will be treated as a total
# number of bits to flip in inputfile. If bits is <1, it will be treated
# as a percentage - ie, -b 0.01 will flip 1% of the total bits in inputfile.
#
# Filefuzz will tell you which bits it flipped (by offset address) in its
# report to STDOUT. If -r is specified, it will dump a bits flipped report
# to outputfile.fuzzreport.txt.

use strict;
use warnings;
use Getopt::Long qw(:config auto_version auto_help);
use Pod::Usage;

my %args = ('i' => '', 'b' => '', 'o' => '');
GetOptions (\%args, "i=s", "b=s", "o=s", "r", "help") or pod2usage(2);

if (defined($args{'help'})) { pod2usage(2); exit 127; }

# is inputfile a file? also, NOT a directory?
if ( !(-f $args{'i'}) || -d $args{'i'}) { 
	warn "$args{'i'} is not a valid input file!\n\n";
	pod2usage(2); exit 127; 
}

# has outputfile been set?
if ($args{'o'} eq '') {
	warn "Outputfile must be set with -o!\b\b";
	podusage(2); exit 127;
}

# does outputfile already exist?
if (-f $args{'o'}) {
	warn "I will not overwrite existing file $args{'o'}.\n\n";
	pod2usage(2); exit 127;
}

# has -b been set?
if ($args{'b'} eq '') {
	warn "You must use -b to tell me how many bits to flip in $args{'i'}.\n\n";
	pod2usage(2); exit 127;
}


print "inputfile: $args{'i'}\n";
print "bits: $args{'b'}\n";
print "outputfile: $args{'o'}\n";
if (defined($args{'r'})) { print "Reporting to $args{'o'}.fuzzreport.txt\n"; }


__END__

=head1 NAME

fuzzfile - a bit flipping tool for simulating bit rot

=head1 SYNOPSIS

fuzzfile -i inputfile -o outputfile -b bits [-r]

Options:

  -i inputfile		the source file to be fuzzed
  -o outputfile		the target filespec to save the fuzzed file
  -b bits		how many bits to flip in inputfile. may be
			absolute number, or percentage
  -r			optional: dump after-action report specifying all 
			bits flipped to outputfile.fuzzreport.txt

  --help		you're reading it now
