#!/usr/bin/perl

# filefuzz flips a certain number of randomly chosen bits in a file, 
# simulating the impact of random small-scale data degradation from eg
# cosmic rays, cable or controller imperfections, etc.
#
# USAGE: filefuzz -i inputfile -b bits -o outputfile [-r [reportfile]]
#
# If bits is greater than or equal to 1, it will be treated as a total
# number of bits to flip in inputfile. If bits is <1, it will be treated
# as a percentage - ie, -b 0.01 will flip 1% of the total bits in inputfile.
#
# Filefuzz will tell you which bits it flipped (by offset address) in its
# report to STDOUT. If -r reportfile is specified, it will dump the report
# to that file instead. If -r is specified with no reportfile, it will
# dump the report to outputfile.fuzzreport.txt.

use strict;
use warnings;
use Getopt::Long qw(:config auto_version auto_help);
use Pod::Usage;

my %args = ('i' => '', 'b' => 0, 'o' => '', 'r' => '||||');
GetOptions (\%args, "i=s", "b=f", "o=s", "r=s");

print "inputfile: $args{'i'}\n";
print "bits: $args{'b'}\n";
print "outputfile: $args{'o'}\n";
print "reportfile: $args{'r'}\n";
